# Generated by Django 4.1.1 on 2022-10-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_date1', models.CharField(blank=True, max_length=20, null=True)),
                ('class_date2', models.CharField(blank=True, max_length=20, null=True)),
                ('class_time1', models.TimeField(blank=True, max_length=50, null=True)),
                ('class_time2', models.TimeField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('user_phonenum', models.CharField(max_length=100, null=True)),
                ('feedback_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_unit', models.CharField(max_length=20)),
                ('class_date1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date1', to='getherapp.class')),
                ('class_date2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date2', to='getherapp.class')),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getherapp.class')),
                ('class_time1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time1', to='getherapp.class')),
                ('class_time2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time2', to='getherapp.class')),
                ('professor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='getherapp.professor')),
            ],
        ),
    ]
