# Generated by Django 4.1.2 on 2022-10-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_content',
            field=models.TextField(default='글을 작성해주세요.'),
        ),
    ]
