# Generated by Django 4.0.4 on 2022-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_phonenum',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
