# Generated by Django 4.1.2 on 2022-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
