# Generated by Django 4.0.4 on 2022-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0002_feedback_user_phonenum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='class_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
