# Generated by Django 4.0.4 on 2022-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0003_class_class_date_class_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
