# Generated by Django 4.0.4 on 2022-05-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0006_alter_class_class_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='professor_id',
        ),
    ]
