# Generated by Django 4.0.4 on 2022-05-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0007_remove_class_class_id_remove_professor_professor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date', to='getherapp.class'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='getherapp.class'),
        ),
    ]
