# Generated by Django 4.0.4 on 2022-05-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0008_classroom_class_date_classroom_class_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='classroom_id',
        ),
    ]
