# Generated by Django 4.0.4 on 2022-05-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0009_remove_classroom_classroom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_date',
            new_name='class_date1',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='class_date',
        ),
        migrations.AddField(
            model_name='class',
            name='class_date2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_date1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date1', to='getherapp.class'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_date2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date2', to='getherapp.class'),
        ),
    ]
