# Generated by Django 4.0.4 on 2022-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0010_rename_class_date_class_class_date1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='time3',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
