# Generated by Django 4.0.4 on 2022-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0011_class_time3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='time3',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_date1',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_date2',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
    ]
