# Generated by Django 4.0.4 on 2022-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0012_remove_class_time3_alter_class_class_date1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_date1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_date2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_time',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
