# Generated by Django 4.0.4 on 2022-05-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getherapp', '0013_alter_class_class_date1_alter_class_class_date2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_time',
            new_name='class_time1',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='class_time',
        ),
        migrations.AddField(
            model_name='class',
            name='class_time2',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_time1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time1', to='getherapp.class'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_time2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time2', to='getherapp.class'),
        ),
    ]
