# Generated by Django 4.1.2 on 2022-10-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lostapp.lost')),
            ],
        ),
    ]
